---
- name: Copy the repository configuration file
  copy:
    src: mongodb.org-5.0.repo
    dest: /etc/yum.repos.d/

- name: Upgrade
  yum:
    name: "*"
    state: latest

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: latest

- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes

- name: Add line to mongod.service file
  lineinfile:
    path: /usr/lib/systemd/system/mongod.service
    line: ExecStartPre=/bin/sh -c "echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled"
    create: yes

- name: Remove line from file if exists
  lineinfile:
    path: /etc/mongod.conf
    line: "^security:"
    state: present
  check_mode: yes
  register: conf

- name: Enable authorization
  lineinfile:
    path: /etc/mongod.conf
    regexp: "^#security:"
    line: "security:\n  authorization: enabled"
  when: (conf is changed) or (conf is failed)

- name: Update the information of Systemd services
  systemd:
    name: mongod
    daemon_reload: True
    state: restarted

- include_tasks: user.yml
