---
- name: Install gnupg
  apt:
    name: gnupg
    state: latest

- name: Import the GPG key of MongoDB
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ version }}.asc"
    state: present

- name: Enable the MongoDB repository
  lineinfile:
    path: "/etc/apt/sources.list.d/mongodb-org-{{ version }}.list"
    line: "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/{{ version }} main"
    create: yes

- name: Update the repository
  apt:
    update_cache: yes

- name: Install Python3
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-pip
    - python2
    - python-pip

- name: Install pymongo
  pip:
    name: pymongo
    state: latest
