---
- name: RedHat - Copy the repository configuration file
  copy:
    src: mongodb.org-5.0.repo
    dest: /etc/yum.repos.d/

- name: RedHat - Upgrade
  yum:
    name: "*"
    state: latest

- name: RedHat - Install Python3
  yum:
    name: python3
    state: latest

- name: RedHat - Install pymongo
  pip:
    name: pymongo
    state: latest
