---
- name: RedHat - Copy the repository configuration file
  copy:
    src: mongodb.org.repo
    dest: "/etc/yum.repos.d/mongodb.org-{{ version }}.repo"

- name: Specify in repo file the version
  replace:
    path: "/etc/yum.repos.d/mongodb.org-{{ version }}.repo"
    regexp: mdbversion
    replace: "{{ version }}"

- name: RedHat - Upgrade
  yum:
    name: "*"
    state: latest

- name: RedHat - Install Python3
  yum:
    name: python3
    state: latest

- name: RedHat - Install pymongo
  pip:
    name: pymongo
    state: latest
