---
- name: Debian - Install gnupg
  apt:
    name: gnupg
    state: latest

- name: Debian - Import the GPG key of MongoDB
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ version }}.asc"
    state: present

- name: Debian - Enable the MongoDB repository
  lineinfile:
    path: "/etc/apt/sources.list.d/mongodb-org-{{ version }}.list"
    line: "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/{{ version }} main"
    create: yes



- name: Debian - Update the repository
  apt:
    update_cache: yes

- name: Debian - Install Python3
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3
    - python3-pip
    - python2-pip

- name: Debian - Install pymongo
  pip:
    name: pymongo
    version: "{{ pymongo_v }}"
    state: present
