---
- name: RedHat - Copy the repository configuration file
  run_once: true
  copy:
    src: mongodb.org.repo
    dest: "/etc/yum.repos.d/mongodb.org-{{ version }}.repo"
  delegate_to: localhost

- name: RedHat - Specify in repo file the version
  run_once: true
  replace:
    path: "/etc/yum.repos.d/mongodb.org-{{ version }}.repo"
    regexp: mdbversion
    replace: "{{ version }}"
  delegate_to: localhost

- name: RedHat - Upgrade
  run_once: true
  yum:
    name: "*"
    state: latest
  delegate_to: localhost

- name: RedHat - Install pymongo
  run_once: true
  pip:
    name: pymongo
    version: "{{ pymongo_v }}"
    state: present
  delegate_to: localhost

- name: RedHat - Install MongoDB client
  run_once: true
  yum:
    name: mongodb-org-shell
    state: latest
  delegate_to: localhost
