---
- name: check mongodb
  run_once: true
  package:
    name: mongodb-org
    state: present
  check_mode: true
  register: result
  ignore_errors: true
  delegate_to: localhost

- include_tasks: install.yml
  when: result.failed
