---
- name: check mongodb
  local_action:
    module: package
    name: mongodb-org
    state: present
  check_mode: true
  register: result
  ignore_errors: true

- include_tasks: install.yml
  when: result.failed
