---
- name: RedHat - Install firewalld
  yum:
    name: firewalld
    state: latest
  notify: start firewalld

- meta: flush_handlers

- name: RedHat - Allow mongodb service in firewalld
  firewalld:
    zone: public
    service: mongodb
    permanent: true
    state: enabled
  notify: reload firewalld

- meta: flush_handlers
