---
- name: Install ufw
  apt:
    name: ufw
    state: latest
  notify: start ufw

- name: Flush handlers
  meta: flush_handlers

- name: Allow ssh service
  ufw:
    rule: allow
    name: ssh

- name: Allow mongodb service in firewall
  ufw:
    rule: allow
    port: 27017
    proto: tcp
  notify: reload ufw

- name: Enable ufw
  ufw:
    state: enabled

- name: Flush handlers
  meta: flush_handlers
