---
- name: Debian - Install ufw
  apt:
    name: ufw
    state: latest
  notify: start ufw

- meta: flush_handlers

- name: Debian - Allow ssh service
  ufw:
    rule: allow
    name: ssh

- name: Debian - Open MogoDB port
  ufw:
    rule: allow
    port: 27017
    proto: tcp
  notify: reload ufw

- name: Debian - Enable ufw
  ufw:
    state: enabled

- meta: flush_handlers
