---
- name: Install firewalld
  yum:
    name: firewalld
    state: latest
  notify: start firewalld

- name: Flush handlers
  meta: flush_handlers

- name: Allow mongodb service in firewalld
  firewalld:
    zone: public
    service: mongodb
    permanent: true
    state: enabled
  notify: reload firewalld

- name: Flush handlers
  meta: flush_handlers
