---
- name: Copy mongod.service file
  copy:
    src: mongod.service
    dest: /lib/systemd/system/mongod.service
  when: ansible_os_family == "RedHat"

- name: Copy configuration file
  copy:
    src: "{{ ansible_os_family}}-mongod.conf"
    dest: /etc/mongod.conf
  notify: restart mongodb

- meta: flush_handlers
